### ISSUE TITLE
Crash on OOS 14

### ISSUE THREAD

**Issue by NripPrajapat** [sosauce/CuteMusic#10]
If I allow 'music permission', it hangs.

If I deny the 'music permission', it will let me go in setting. 

But it crashes when I change to 'amoled mode' and 'swipe gestures'.

I'm on Android 14, OnePlus 8T.
P.S. - It won't show any of the music files.

**Comment by sosauce** [comment]
Do you mean access music permission ? Because the app doesnt use the notification permission

**Comment by NripPrajapat** [comment]
Yes, I edited it.

**Comment by sosauce** [comment]
Could I have a sreen recording of the issues please ? I can't reproduce them

**Comment by NripPrajapat** [comment]
https://github.com/sosauce/CuteMusic/assets/165571761/a52b3cc3-8fb1-4660-9a0a-d6d4ae19556d


https://github.com/sosauce/CuteMusic/assets/165571761/b6d6a526-d57f-4f36-85b6-58e89b8d3190

It occurs when I given 'music' permission.

**Comment by NripPrajapat** [comment]
Maybe it's OOS, but other apps that uses Amoled stuff works well, find and try to fix it, BTW music in root storage://'music'folder.

**Comment by sosauce** [comment]
Mhm okay, hopefully MediaStore scan this folder. What type are your musics ? (MP3, OGG etc..) Sorry for all the questions but it helps me save time in research 😁

**Comment by NripPrajapat** [comment]
It's okay, ask all the questions, that you have, it'll only make the app and experience better.

Yes, I have m4a, mp3, FLAC and ogg too.

**Comment by sosauce** [comment]
Okay, Exoplayer (the medi player used by Android) should support all these files. Thanks!

**Comment by NripPrajapat** [comment]
It will not standout, if you use the same stuff, that android, automatically does. Be genuine.

**Comment by sosauce** [comment]
Oh I think i wsn't clear sorry. Exoplayer is the "engine" that decodes the audio files to be able to play them. All apps that displaye music/videos (like youtube for example) use it, because if they don't, the app wont be able to play the content

**Comment by NripPrajapat** [comment]
Some apps use their own encoders. Maybe you should think of it too.

**Comment by sosauce** [comment]
Honestly there's no reason to. It's a hard thing to code. At least ExoPlayer is made by Google so I know it stable an reliable

**Comment by sosauce** [comment]
Also, do you have Discord ? I think I have fixed the issues and would like to send you an APK for you to test

**Comment by sosauce** [comment]
Here's a Drive link. Please note it's a unfinished APK, so after testing you should uninstall it
https://drive.google.com/file/d/1SS8bJLF4B1Qjs-RUg88dTt3lvCWjDKq1/view?usp=drive_link

**Comment by NripPrajapat** [comment]
It needs permission, so grant it.

**Comment by sosauce** [comment]
I gave access

**Comment by NripPrajapat** [comment]
It still happens, the "crash", it all works well after I 'revoke' the permission.

It surely displays the audio files now, but it keeps hanging. Not working at all, I can't play a second with the app.

**Comment by sosauce** [comment]
Can you send a screen recording again ? (sorry) Because its an unfinished APK so it might be temporary

**Comment by NripPrajapat** [comment]
https://github.com/sosauce/CuteMusic/assets/165571761/27c1ab94-2f8d-4690-bff4-faf325f18053

**Comment by NripPrajapat** [comment]
https://github.com/sosauce/CuteMusic/assets/165571761/35c7914e-72ce-4d89-9c64-57d97edf7bef

**Comment by NripPrajapat** [comment]
In the 1.1.1, the problem is actually with 'amoled mode', app is taking time to load files at start, but it works fine after.

**Comment by sosauce** [comment]
Okay, so no problem/crash except with amoled ?

**Comment by NripPrajapat** [comment]
That is correct. 

https://github.com/sosauce/CuteMusic/assets/165571761/4c00d560-61cb-4e6c-8a83-28d6b148c031

**Comment by sosauce** [comment]
https://drive.google.com/file/d/1aIUPfVGWc8OLr5A55nHmlMYDeGDSQ3Mb/view?usp=sharing

Could you try this APK and tell me if musics load faster please ?

**Comment by NripPrajapat** [comment]
Yes, it surely does, but it won't load album and artists.

**Comment by NripPrajapat** [comment]
And it won't crash anymore with 'amoled' mode on. 😁

**Comment by NripPrajapat** [comment]
Force closing the app and restarting helps for sure.

**Comment by sosauce** [comment]
Yes, It's normal in the APK I gave you I removed the get albums and artists, it was just to see if musics loads faster, you should remove it now ^^

**Comment by NripPrajapat** [comment]
Okay

**Comment by sosauce** [comment]
Hi! It's been a while, but can you test this : https://drive.google.com/file/d/1Y4HOrKWAyZnUjFPWWbSp1uVuo3ybPIZ_/view?usp=sharing

Should have optimized and change some things, wanna know how it goes for you !

**Comment by NripPrajapat** [comment]
No lag at all.

**Comment by sosauce** [comment]
🥳 Release tomorrow then !!

**Comment by NripPrajapat** [comment]
Are artists and album features hidden purposely?

**Comment by sosauce** [comment]
Uhm, what do you mean ?

**Comment by NripPrajapat** [comment]
It says, no album found, no artists found.

**Comment by sosauce** [comment]
Relaunch the app, if it doesnt help, maybe a bug if there's too much albums/artists

**Comment by NripPrajapat** [comment]
Nothing at all. No change.
Restarted manually, tried app 'restart'.
Cleared data. Nothing.
